### ISSUE TITLE
[NH-010] - Paginate the search API response

### ISSUE THREAD

**Issue by danielmasegosa** [needlehack-team/needlehack#10]

**Comment by david-romero** [comment]
We need to create a CommandLineRunner for creating an index at startup. This index is needed in order to decouple the collector to the search api component since if we run the search api component without the collector being running, the result will be a failed execution.

Further information is available here:
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-create-index.html
